"""AgentBlueprint — the complete profile generated by AgentWizard."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class TestScenario:
    """A single validation scenario for a freshly-created agent."""

    name: str
    prompt: str
    expected_keywords: list[str] = field(default_factory=list)
    expected_tool_calls: list[str] = field(default_factory=list)
    max_turns: int = 1


@dataclass
class AgentBlueprint:
    """Immutable profile describing how to build an agent.

    Created by :class:`AgentWizardService`, persisted to YAML, and consumed by
    :class:`AgentFactory`.
    """

    name: str
    role: str = "executor"  # executor | supervisor | specialist
    team_function: str = ""  # "code reviewer", "researcher", …
    persona_prompt: str = ""
    system_prompt_template: str = ""
    required_skills: list[str] = field(default_factory=list)
    required_tools: list[str] = field(default_factory=list)
    suggested_model: str = ""
    suggested_backend: str = "ollama"  # "ollama" | "openai"
    initial_permissions: dict[str, Any] = field(default_factory=dict)
    test_scenarios: list[TestScenario] = field(default_factory=list)
    communication_style: str = "balanced"  # "formal" | "casual" | "balanced"
    metadata: dict[str, Any] = field(default_factory=dict)

    # ---- serialization helpers ----

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "role": self.role,
            "team_function": self.team_function,
            "persona_prompt": self.persona_prompt,
            "system_prompt_template": self.system_prompt_template,
            "required_skills": self.required_skills,
            "required_tools": self.required_tools,
            "suggested_model": self.suggested_model,
            "suggested_backend": self.suggested_backend,
            "initial_permissions": self.initial_permissions,
            "test_scenarios": [
                {
                    "name": ts.name,
                    "prompt": ts.prompt,
                    "expected_keywords": ts.expected_keywords,
                    "expected_tool_calls": ts.expected_tool_calls,
                    "max_turns": ts.max_turns,
                }
                for ts in self.test_scenarios
            ],
            "communication_style": self.communication_style,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AgentBlueprint":
        scenarios = [
            TestScenario(**s)
            for s in data.get("test_scenarios", [])
        ]
        return cls(
            name=data.get("name", ""),
            role=data.get("role", "executor"),
            team_function=data.get("team_function", ""),
            persona_prompt=data.get("persona_prompt", ""),
            system_prompt_template=data.get("system_prompt_template", ""),
            required_skills=data.get("required_skills", []),
            required_tools=data.get("required_tools", []),
            suggested_model=data.get("suggested_model", ""),
            suggested_backend=data.get("suggested_backend", "ollama"),
            initial_permissions=data.get("initial_permissions", {}),
            test_scenarios=scenarios,
            communication_style=data.get("communication_style", "balanced"),
            metadata=data.get("metadata", {}),
        )
